replicaCount: 3
grpcPort: 50000
restPort: 9090
kubeMQPort: 8080
clusterPort: 5228
token: null 

image:
  repository: kubemq/kubemq
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  
